### ISSUE TITLE
ElvUI Plugin overlapping

### ISSUE THREAD

**Issue by MarcelT87** [cdmichaelb/Outfitter#122]
Hello,

would it be possible to put the anchorpoint of Outfitter next to the Elvui plugin? See screenshot

![Unbenannt](https://user-images.githubusercontent.com/105316958/200141277-5ae69626-834d-4666-8589-1ae47308daf3.JPG)

**Comment by Gogo1951** [comment]
Hey @MarcelT87 

I don't know what the desired outcome is here. We need to anchor the Outfitter menu to the character sheet, and you're bolting on the other panel using Elv. There are a lot of add-ons that try and use this space, and in my opinion, none of them should be doing that. We can't bolt the menu to the panel they create... we'd have to take the button out of the character sheet... dunno, seems like a lot of work, all because they did a dumb we have to adapt? =P Just sort of the way it feels.

Noticed this with a bunch of add-ons... RestedXP has a panel there, a bunch of character stat summaries are trying to use that space, and there are weak auras that show if you're saved or not. Dumb place for them all to put things. Not sure what we can do. Go to each of those add-ons and call them dummies? (= I'm not sure, they're all going to have conflicts with each other too.
