### ISSUE TITLE
The pop-out slots are missing from 1.13

### ISSUE THREAD

**Issue by lvangh** [cdmichaelb/Outfitter#19]
In 1.12 when you click on an item slot you get a pop-out menu with similar items for that slot. Here is a screenshot from 1.12 Outfitter to demonstrate. 

![image](https://user-images.githubusercontent.com/19690096/83959935-a26de480-a837-11ea-85ff-a50d607a4230.png)

This is missing in 1.13, and the only workaround is to have ItemRack installed as well since it provides a popout, but this often creates issues with gear sets.

**Comment by cdmichaelb** [comment]
I'll try to implement it, the code is entirely different from vanilla and
from retail.

**Comment by atlings** [comment]
Take a look at alagearman -- it has this functionality (make or break imo)

**Comment by Nitti2909** [comment]
I really hope your gonna fix this, i was a fanatic user of Outfitter in retail, but in Classic i have to use Itemrack do to this function missing from Outfitter.
@Ivangh: Ive tried installing all versions of Outfitter from ver 12.0 to 13.0 and i never saw the popout function, so i think your screenshoot shows something from another addon (Altho i have to say the frames looks alot like outfitters).

**Comment by cdmichaelb** [comment]
@Nitti2909 I think it's outfitter from vanilla wow. I do plan to add it eventually, I admit that I currently run item rack exclusively for the popout menus. Otherwise I use outfitter for every thing.

With war effort over, and AQ week coming near to being complete I should have some time again to work on this addon.

**Comment by Nitti2909** [comment]
@cdmichaelb, ohh, thx 
I did some testing today as i really dont like Itemrack, mostly do to it missing the "Outfit Bar" and the bank feature sucks...
The "Alagearman" is imo the best option to combine with Outfitter for the popout menu (Just have to press Alt to get the popout). So far i have not found any interference with Outfitter.
Im so happy i can now run Outfitter instead of itemrack, Yeahhhh:-)))
