### ISSUE TITLE
Hunter Feign/Skinning not working

### ISSUE THREAD

**Issue by leemanpa** [cdmichaelb/Outfitter#21]
Feign Death does not change set, nor does a skinning set I manually switch to when skinning 315 or 310 LW. Manual button on icon bar is fine, just no auto switch.

**Comment by cdmichaelb** [comment]
I don't see any reason for either of them not to work. I'll have to research FD some more. But skinning, you likely have an addon controlling tooltips. Because of the way interactions with other addons works, it'll be unlikely to code it to work with your specific tooltip addon. If you tell me which addon I can do my best to support it. Currently it supports base wow tooltips, and MobInfo2 tooltips.

**Comment by leemanpa** [comment]
Addons I use that list Tooltip interaction:

Leatrix Plus


Auctioneer


INFORMANT

 

I disabled Informant & the Feign now works. Will let you know when I try the skinning.

Informant seems to be the ToolTip conflict.

**Comment by leemanpa** [comment]
Skinning set still not switching when attempting a 310 or 315 skin
