### ISSUE TITLE
Equip set based on cooldown

### ISSUE THREAD

**Issue by Fridarey** [cdmichaelb/Outfitter#42]
Two of my gear sets are:
 
1. Uses trinket queue
2. Does not use trinket queue
 
Is there a way to have set 2 automatically equipped out of combat when one of the trinks in set one comes off cooldown? If it matters, this trinket is at the top of the queue. Also, this is Classic.
 
Thanks o/

**Comment by lvangh** [comment]
Oh sorry, I think I misunderstood - You want gear swaps based on currently equipped trinket? You can do that with custom Lua but it's a lot of work since you need to get the slot of the trinket, and return the cooldown then perform an equip action if the conditions are met. I think it can be done, sorry thought I was more help than I actually am. 

-ignore I think I misunderstood
Use TrinketMenu instead for this. You can setup queues, auto swaps, priorities etc. 
https://www.wowinterface.com/downloads/info24977-TrinketMenuClassic.html
